//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.24 at 02:38:19 PM VET 
//


package com.iata.iatafuelcodedirectory;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BMTransactionCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BMTransactionCode">
 *   &lt;restriction base="{http://www.IATA.com/IATABaseDataTypeDirectory}AN03Base">
 *     &lt;enumeration value="DO"/>
 *     &lt;enumeration value="CI"/>
 *     &lt;enumeration value="MI"/>
 *     &lt;enumeration value="HO"/>
 *     &lt;enumeration value="ST"/>
 *     &lt;enumeration value="GR"/>
 *     &lt;enumeration value="VE"/>
 *     &lt;enumeration value="CL"/>
 *     &lt;enumeration value="CA"/>
 *     &lt;enumeration value="OW"/>
 *     &lt;enumeration value="TE"/>
 *     &lt;enumeration value="PH"/>
 *     &lt;enumeration value="CO"/>
 *     &lt;enumeration value="PU"/>
 *     &lt;enumeration value="AD"/>
 *     &lt;enumeration value="RE"/>
 *     &lt;enumeration value="RF"/>
 *     &lt;enumeration value="PR"/>
 *     &lt;enumeration value="LO"/>
 *     &lt;enumeration value="LB"/>
 *     &lt;enumeration value="RT"/>
 *     &lt;enumeration value="SA"/>
 *     &lt;enumeration value="LM"/>
 *     &lt;enumeration value="PT"/>
 *     &lt;enumeration value="FD"/>
 *     &lt;enumeration value="BK"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BMTransactionCode", namespace = "http://www.IATA.com/IATAFuelCodeDirectory")
@XmlEnum
public enum BMTransactionCode {

    DO,
    CI,
    MI,
    HO,
    ST,
    GR,
    VE,
    CL,
    CA,
    OW,
    TE,
    PH,
    CO,
    PU,
    AD,
    RE,
    RF,
    PR,
    LO,
    LB,
    RT,
    SA,
    LM,
    PT,
    FD,
    BK;

    public String value() {
        return name();
    }

    public static BMTransactionCode fromValue(String v) {
        return valueOf(v);
    }

}
