//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.24 at 02:38:19 PM VET 
//


package com.iata.iatafuelcodedirectory;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InvoiceIDType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="InvoiceIDType">
 *   &lt;restriction base="{http://www.IATA.com/IATABaseDataTypeDirectory}AN02Base">
 *     &lt;enumeration value="II"/>
 *     &lt;enumeration value="BT"/>
 *     &lt;enumeration value="PY"/>
 *     &lt;enumeration value="SF"/>
 *     &lt;enumeration value="ST"/>
 *     &lt;enumeration value="AF"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "InvoiceIDType", namespace = "http://www.IATA.com/IATAFuelCodeDirectory")
@XmlEnum
public enum InvoiceIDType {

    II,
    BT,
    PY,
    SF,
    ST,
    AF;

    public String value() {
        return name();
    }

    public static InvoiceIDType fromValue(String v) {
        return valueOf(v);
    }

}
