//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.24 at 02:38:19 PM VET 
//


package com.iata.iatafuelcodedirectory;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductIDBase.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ProductIDBase">
 *   &lt;restriction base="{http://www.IATA.com/IATABaseDataTypeDirectory}AN05Base">
 *     &lt;enumeration value="ADT"/>
 *     &lt;enumeration value="ADTV"/>
 *     &lt;enumeration value="AG100"/>
 *     &lt;enumeration value="AG1HL"/>
 *     &lt;enumeration value="AG80"/>
 *     &lt;enumeration value="AHF"/>
 *     &lt;enumeration value="AIF"/>
 *     &lt;enumeration value="APT"/>
 *     &lt;enumeration value="ATT"/>
 *     &lt;enumeration value="CHN"/>
 *     &lt;enumeration value="CNF"/>
 *     &lt;enumeration value="CNT"/>
 *     &lt;enumeration value="COM"/>
 *     &lt;enumeration value="CON"/>
 *     &lt;enumeration value="CSF"/>
 *     &lt;enumeration value="CUF"/>
 *     &lt;enumeration value="DEF"/>
 *     &lt;enumeration value="DEH"/>
 *     &lt;enumeration value="DIS"/>
 *     &lt;enumeration value="DMF"/>
 *     &lt;enumeration value="ENV"/>
 *     &lt;enumeration value="FLF"/>
 *     &lt;enumeration value="FRF"/>
 *     &lt;enumeration value="GSF"/>
 *     &lt;enumeration value="HNG"/>
 *     &lt;enumeration value="HUF"/>
 *     &lt;enumeration value="HYD"/>
 *     &lt;enumeration value="INF"/>
 *     &lt;enumeration value="INS"/>
 *     &lt;enumeration value="ITP"/>
 *     &lt;enumeration value="JA1A"/>
 *     &lt;enumeration value="JAA"/>
 *     &lt;enumeration value="JETA"/>
 *     &lt;enumeration value="JETA1"/>
 *     &lt;enumeration value="JP4"/>
 *     &lt;enumeration value="JP5"/>
 *     &lt;enumeration value="JP8"/>
 *     &lt;enumeration value="JSF"/>
 *     &lt;enumeration value="LVF"/>
 *     &lt;enumeration value="MVF"/>
 *     &lt;enumeration value="NFF"/>
 *     &lt;enumeration value="NON"/>
 *     &lt;enumeration value="OFF"/>
 *     &lt;enumeration value="OTH"/>
 *     &lt;enumeration value="OVT"/>
 *     &lt;enumeration value="OWF"/>
 *     &lt;enumeration value="PLF"/>
 *     &lt;enumeration value="REB"/>
 *     &lt;enumeration value="STR"/>
 *     &lt;enumeration value="SYS"/>
 *     &lt;enumeration value="THP"/>
 *     &lt;enumeration value="TPF"/>
 *     &lt;enumeration value="TRF"/>
 *     &lt;enumeration value="TS1"/>
 *     &lt;enumeration value="EWF"/>
 *     &lt;enumeration value="FMJ"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ProductIDBase", namespace = "http://www.IATA.com/IATAFuelCodeDirectory")
@XmlEnum
public enum ProductIDBase {

    ADT("ADT"),
    ADTV("ADTV"),
    @XmlEnumValue("AG100")
    AG_100("AG100"),
    @XmlEnumValue("AG1HL")
    AG_1_HL("AG1HL"),
    @XmlEnumValue("AG80")
    AG_80("AG80"),
    AHF("AHF"),
    AIF("AIF"),
    APT("APT"),
    ATT("ATT"),
    CHN("CHN"),
    CNF("CNF"),
    CNT("CNT"),
    COM("COM"),
    CON("CON"),
    CSF("CSF"),
    CUF("CUF"),
    DEF("DEF"),
    DEH("DEH"),
    DIS("DIS"),
    DMF("DMF"),
    ENV("ENV"),
    FLF("FLF"),
    FRF("FRF"),
    GSF("GSF"),
    HNG("HNG"),
    HUF("HUF"),
    HYD("HYD"),
    INF("INF"),
    INS("INS"),
    ITP("ITP"),
    @XmlEnumValue("JA1A")
    JA_1_A("JA1A"),
    JAA("JAA"),
    JETA("JETA"),
    @XmlEnumValue("JETA1")
    JETA_1("JETA1"),
    @XmlEnumValue("JP4")
    JP_4("JP4"),
    @XmlEnumValue("JP5")
    JP_5("JP5"),
    @XmlEnumValue("JP8")
    JP_8("JP8"),
    JSF("JSF"),
    LVF("LVF"),
    MVF("MVF"),
    NFF("NFF"),
    NON("NON"),
    OFF("OFF"),
    OTH("OTH"),
    OVT("OVT"),
    OWF("OWF"),
    PLF("PLF"),
    REB("REB"),
    STR("STR"),
    SYS("SYS"),
    THP("THP"),
    TPF("TPF"),
    TRF("TRF"),
    @XmlEnumValue("TS1")
    TS_1("TS1"),
    EWF("EWF"),
    FMJ("FMJ");
    private final String value;

    ProductIDBase(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ProductIDBase fromValue(String v) {
        for (ProductIDBase c: ProductIDBase.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
