//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.24 at 02:38:19 PM VET 
//


package com.iata.iatafuelcodedirectory;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductIDQualifier.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ProductIDQualifier">
 *   &lt;restriction base="{http://www.IATA.com/IATABaseDataTypeDirectory}AN04Base">
 *     &lt;enumeration value="PRDT"/>
 *     &lt;enumeration value="FEE"/>
 *     &lt;enumeration value="OTHR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ProductIDQualifier", namespace = "http://www.IATA.com/IATAFuelCodeDirectory")
@XmlEnum
public enum ProductIDQualifier {

    PRDT,
    FEE,
    OTHR;

    public String value() {
        return name();
    }

    public static ProductIDQualifier fromValue(String v) {
        return valueOf(v);
    }

}
