//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.24 at 02:38:19 PM VET 
//


package com.iata.iatafuelcodedirectory;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PureIntoPlaneCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PureIntoPlaneCode">
 *   &lt;restriction base="{http://www.IATA.com/IATABaseDataTypeDirectory}AN05Base">
 *     &lt;enumeration value="AFO"/>
 *     &lt;enumeration value="AFS"/>
 *     &lt;enumeration value="AIB"/>
 *     &lt;enumeration value="AMA"/>
 *     &lt;enumeration value="ASIG"/>
 *     &lt;enumeration value="ATL"/>
 *     &lt;enumeration value="BAF"/>
 *     &lt;enumeration value="BAN"/>
 *     &lt;enumeration value="BASB"/>
 *     &lt;enumeration value="CIB"/>
 *     &lt;enumeration value="CIS"/>
 *     &lt;enumeration value="COM"/>
 *     &lt;enumeration value="CTI"/>
 *     &lt;enumeration value="ECA"/>
 *     &lt;enumeration value="EJA"/>
 *     &lt;enumeration value="EMA"/>
 *     &lt;enumeration value="EMO"/>
 *     &lt;enumeration value="FIA"/>
 *     &lt;enumeration value="GAV"/>
 *     &lt;enumeration value="GFC"/>
 *     &lt;enumeration value="GFS"/>
 *     &lt;enumeration value="GLG"/>
 *     &lt;enumeration value="GRS"/>
 *     &lt;enumeration value="GVFS"/>
 *     &lt;enumeration value="HAF"/>
 *     &lt;enumeration value="HOY"/>
 *     &lt;enumeration value="HPC"/>
 *     &lt;enumeration value="HRS"/>
 *     &lt;enumeration value="IJV"/>
 *     &lt;enumeration value="JAZ"/>
 *     &lt;enumeration value="JIA"/>
 *     &lt;enumeration value="JOC"/>
 *     &lt;enumeration value="KAF"/>
 *     &lt;enumeration value="KLI"/>
 *     &lt;enumeration value="KPL"/>
 *     &lt;enumeration value="MAF"/>
 *     &lt;enumeration value="MAR"/>
 *     &lt;enumeration value="MFS"/>
 *     &lt;enumeration value="OAS"/>
 *     &lt;enumeration value="OIC"/>
 *     &lt;enumeration value="OMA"/>
 *     &lt;enumeration value="PLH"/>
 *     &lt;enumeration value="SAC"/>
 *     &lt;enumeration value="SAF"/>
 *     &lt;enumeration value="SFC"/>
 *     &lt;enumeration value="SFI"/>
 *     &lt;enumeration value="SFS"/>
 *     &lt;enumeration value="SIG"/>
 *     &lt;enumeration value="SJJ"/>
 *     &lt;enumeration value="SJS"/>
 *     &lt;enumeration value="SKY"/>
 *     &lt;enumeration value="SSF"/>
 *     &lt;enumeration value="TAA"/>
 *     &lt;enumeration value="UPS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PureIntoPlaneCode", namespace = "http://www.IATA.com/IATAFuelCodeDirectory")
@XmlEnum
public enum PureIntoPlaneCode {

    AFO,
    AFS,
    AIB,
    AMA,
    ASIG,
    ATL,
    BAF,
    BAN,
    BASB,
    CIB,
    CIS,
    COM,
    CTI,
    ECA,
    EJA,
    EMA,
    EMO,
    FIA,
    GAV,
    GFC,
    GFS,
    GLG,
    GRS,
    GVFS,
    HAF,
    HOY,
    HPC,
    HRS,
    IJV,
    JAZ,
    JIA,
    JOC,
    KAF,
    KLI,
    KPL,
    MAF,
    MAR,
    MFS,
    OAS,
    OIC,
    OMA,
    PLH,
    SAC,
    SAF,
    SFC,
    SFI,
    SFS,
    SIG,
    SJJ,
    SJS,
    SKY,
    SSF,
    TAA,
    UPS;

    public String value() {
        return name();
    }

    public static PureIntoPlaneCode fromValue(String v) {
        return valueOf(v);
    }

}
