//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.24 at 02:38:19 PM VET 
//


package com.iata.iatafuelcodedirectory;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SupplierOROwnerCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SupplierOROwnerCode">
 *   &lt;restriction base="{http://www.IATA.com/IATABaseDataTypeDirectory}AN05Base">
 *     &lt;enumeration value="ABP"/>
 *     &lt;enumeration value="ADN"/>
 *     &lt;enumeration value="AEF"/>
 *     &lt;enumeration value="AFP"/>
 *     &lt;enumeration value="AGL"/>
 *     &lt;enumeration value="AGP"/>
 *     &lt;enumeration value="AIR"/>
 *     &lt;enumeration value="AMH"/>
 *     &lt;enumeration value="AMP"/>
 *     &lt;enumeration value="ARA"/>
 *     &lt;enumeration value="ARC"/>
 *     &lt;enumeration value="ASA"/>
 *     &lt;enumeration value="BAK"/>
 *     &lt;enumeration value="BAP"/>
 *     &lt;enumeration value="BAW"/>
 *     &lt;enumeration value="BHP"/>
 *     &lt;enumeration value="CAA"/>
 *     &lt;enumeration value="CAO"/>
 *     &lt;enumeration value="CEP"/>
 *     &lt;enumeration value="CON"/>
 *     &lt;enumeration value="CPC"/>
 *     &lt;enumeration value="CPT"/>
 *     &lt;enumeration value="CUR"/>
 *     &lt;enumeration value="CVX"/>
 *     &lt;enumeration value="DCM"/>
 *     &lt;enumeration value="DOR"/>
 *     &lt;enumeration value="EIA"/>
 *     &lt;enumeration value="EKO"/>
 *     &lt;enumeration value="ENG"/>
 *     &lt;enumeration value="ENO"/>
 *     &lt;enumeration value="HIP"/>
 *     &lt;enumeration value="IOC"/>
 *     &lt;enumeration value="JAL"/>
 *     &lt;enumeration value="JOP"/>
 *     &lt;enumeration value="KLM"/>
 *     &lt;enumeration value="KOB"/>
 *     &lt;enumeration value="KPC"/>
 *     &lt;enumeration value="LAG"/>
 *     &lt;enumeration value="LUF"/>
 *     &lt;enumeration value="LUK"/>
 *     &lt;enumeration value="MAL"/>
 *     &lt;enumeration value="MIS"/>
 *     &lt;enumeration value="MOL"/>
 *     &lt;enumeration value="MSC"/>
 *     &lt;enumeration value="NEO"/>
 *     &lt;enumeration value="NES"/>
 *     &lt;enumeration value="NKP"/>
 *     &lt;enumeration value="NOC"/>
 *     &lt;enumeration value="NWA"/>
 *     &lt;enumeration value="OMV"/>
 *     &lt;enumeration value="PAS"/>
 *     &lt;enumeration value="PBS"/>
 *     &lt;enumeration value="PCH"/>
 *     &lt;enumeration value="PEG"/>
 *     &lt;enumeration value="PEO"/>
 *     &lt;enumeration value="PEP"/>
 *     &lt;enumeration value="PER"/>
 *     &lt;enumeration value="PFT"/>
 *     &lt;enumeration value="PHF"/>
 *     &lt;enumeration value="POC"/>
 *     &lt;enumeration value="PSO"/>
 *     &lt;enumeration value="QAP"/>
 *     &lt;enumeration value="QAT"/>
 *     &lt;enumeration value="REC"/>
 *     &lt;enumeration value="REP"/>
 *     &lt;enumeration value="SAA"/>
 *     &lt;enumeration value="SAO"/>
 *     &lt;enumeration value="SAS"/>
 *     &lt;enumeration value="SHL"/>
 *     &lt;enumeration value="SIN"/>
 *     &lt;enumeration value="SIP"/>
 *     &lt;enumeration value="SNL"/>
 *     &lt;enumeration value="STA"/>
 *     &lt;enumeration value="SUN"/>
 *     &lt;enumeration value="TAM"/>
 *     &lt;enumeration value="TAP"/>
 *     &lt;enumeration value="TOT"/>
 *     &lt;enumeration value="UAF"/>
 *     &lt;enumeration value="VAL"/>
 *     &lt;enumeration value="WFS"/>
 *     &lt;enumeration value="XOM"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SupplierOROwnerCode", namespace = "http://www.IATA.com/IATAFuelCodeDirectory")
@XmlEnum
public enum SupplierOROwnerCode {

    ABP,
    ADN,
    AEF,
    AFP,
    AGL,
    AGP,
    AIR,
    AMH,
    AMP,
    ARA,
    ARC,
    ASA,
    BAK,
    BAP,
    BAW,
    BHP,
    CAA,
    CAO,
    CEP,
    CON,
    CPC,
    CPT,
    CUR,
    CVX,
    DCM,
    DOR,
    EIA,
    EKO,
    ENG,
    ENO,
    HIP,
    IOC,
    JAL,
    JOP,
    KLM,
    KOB,
    KPC,
    LAG,
    LUF,
    LUK,
    MAL,
    MIS,
    MOL,
    MSC,
    NEO,
    NES,
    NKP,
    NOC,
    NWA,
    OMV,
    PAS,
    PBS,
    PCH,
    PEG,
    PEO,
    PEP,
    PER,
    PFT,
    PHF,
    POC,
    PSO,
    QAP,
    QAT,
    REC,
    REP,
    SAA,
    SAO,
    SAS,
    SHL,
    SIN,
    SIP,
    SNL,
    STA,
    SUN,
    TAM,
    TAP,
    TOT,
    UAF,
    VAL,
    WFS,
    XOM;

    public String value() {
        return name();
    }

    public static SupplierOROwnerCode fromValue(String v) {
        return valueOf(v);
    }

}
